# This file contains values from Cookiecutter

default_context:
  project_name: "simple-css-selector-transform"
  project_description: "Simple transformations for CSS Selectors"
  organization: "Stream HPC B.V."
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "StreamHPC"
  email: "gergely@streamhpc.com"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "none"
